LerianStudio/midaz-console

src/core/application/mappers/product-mapper.ts, src/core/application/use-cases/product/create-product-use-case.ts, src/core/application/use-cases/product/fetch-all-products-use-case.ts, src/core/application/use-cases/product/fetch-product-by-id-use-case.ts, src/core/application/use-cases/product/update-product-use-case.ts, src/core/infrastructure/container-registry/container-registry.ts, src/core/infrastructure/container-registry/products-module.ts
A product refactoring on the core module, using a new class method of implementing mappers and container-registry spliting into multiple files.
=> Product mapper and container refactor

locales/extracted/en.json, locales/extracted/pt.json, src/app/(routes)/ledgers/[id]/assets/assets-sheet.tsx, src/lib/zod/messages.ts, src/schema/assets.ts, src/schema/regex.ts
=> :sparkles: feat: add validation into field code

.githooks/commit-msg/commit-msg, .githooks/pre-commit/pre-commit, .githooks/pre-push/pre-push, .githooks/pre-receive/pre-receive
=> insert githooks

locales/extracted/en.json, locales/extracted/pt.json, src/app/(routes)/ledgers/ledgers-sheet.tsx
=> :recycle: refactor: Added Tabs to Ledger Sheet

src/app/(auth-routes)/signin/page.tsx, src/components/ui/tooltip/index.tsx, src/components/ui/tooltip/tooltip.stories.tsx
=> ♻️ Updated Tooltip design

src/app/(routes)/transactions/[id]/page.tsx, src/app/(routes)/transactions/create/page.tsx, src/app/(routes)/transactions/page.tsx, src/app/api/organizations/[id]/ledgers/[ledgerId]/transactions/[transactionId]/route.ts, src/app/api/organizations/[id]/ledgers/[ledgerId]/transactions/json/route.ts, src/app/api/organizations/[id]/ledgers/[ledgerId]/transactions/route.ts, src/components/sidebar/index.tsx, src/core/infrastructure/container-registry/container-registry.ts, src/core/infrastructure/container-registry/use-cases/transactions-module.ts, src/core/infrastructure/midaz/module/midaz-module.ts, src/core/infrastructure/midaz/module/transaction-module.ts
=> Added Transaction base files

package-lock.json
=> fix: resolving conflicts between package.json and package-lock.json

.github/workflows/build-release.yaml
=> fix: changing the trigger to execute github action WF

.github/workflows/build-release.yaml
- [x ] I have tested these changes locally.
=> fix: improve steps to control the github actions workflow

.gitattributes
=> fix: set gitattributes to untrack LFS files

release.config.js
=> chore: included chore like patch with release type

src/app/api/organizations/[id]/ledgers/[ledgerId]/transactions/json/route.ts, src/core/application/dto/transaction-dto.ts, src/core/application/mappers/transaction-mapper.test.ts, src/core/application/mappers/transaction-mapper.ts, src/core/application/use-cases/accounts-with-portfolios/fetch-accounts-with-portfolios-use-case.ts, src/core/application/use-cases/transactions/create-transaction-use-case.ts, src/core/domain/entities/transaction-entity.ts, src/core/domain/repositories/transactions/create-transaction-repository.ts, src/core/infrastructure/container-registry/use-cases/transactions-module.ts, src/core/infrastructure/midaz/module/transaction-module.ts, src/core/infrastructure/midaz/transactions/midaz-create-transaction-repository.ts
Implementation of the Create Transaction on the core/back-end.
=> ✨ Transaction Create: Back-end implementation

README.md
=> :books:docs: Update midaz documentation links

src/context/organization-provider/index.tsx, src/context/permission-provider/index.tsx, src/lib/fetcher/index.test.ts, src/lib/fetcher/index.ts
=> 💥Fixed bug when Session token expires

locales/extracted/en.json, locales/extracted/pt.json, src/context/permission-provider/route-enforcer.tsx
=> :sparkles: feat: Added not authorized page

src/app/(auth-routes)/signout/page.tsx, src/core/infrastructure/errors/midaz-error.ts, src/core/infrastructure/utils/midaz-error-handler.ts, src/lib/fetcher/index.ts
=> :boom: fix: Fixed token expired issue

locales/extracted/en.json, locales/extracted/pt.json, src/app/(routes)/ledgers/[id]/transactions/create/operation-accordion.tsx, src/app/(routes)/ledgers/[id]/transactions/create/review/page.tsx, src/app/(routes)/ledgers/ledgers-data-table.tsx, src/app/api/organizations/[id]/ledgers/[ledgerId]/transactions/json/route.ts, src/components/transactions/primitives/transaction-receipt.tsx, src/components/ui/paper/index.tsx, src/components/user-dropdown/index.tsx, src/core/application/mappers/transaction-mapper.ts, src/core/infrastructure/midaz/transactions/midaz-create-transaction-repository.ts
=> 💥 Transactions Fixes: precision and logging

src/app/(routes)/settings/organizations/organizations-form-color-field.tsx
- Fixes issue where the ChromePicker moved with page scroll, it now stays anchored using PopoverContent
=> :boom: fix: prevent ChromePicker from moving when scrolling

.github/workflows/pre-release.yml
=> feat: disable commit lint on flow to execute release on main

.github/workflows/pre-release.yml
=> feat: disable codeql temporarily to execute entire flow

.github/workflows/pre-release.yml, CHANGELOG.md
=> Release to main

src/app/(routes)/settings/organizations-tab-content.tsx
- Fix modal not closing after organization deletion
- Fix onSuccess callback typo
=> fix: modal not closing after deleting an organization

src/app/(routes)/accounts/accounts-data-table.tsx, src/app/(routes)/assets/assets-sheet.tsx, src/core/application/use-cases/accounts-with-portfolios/fetch-accounts-with-portfolios-use-case.ts
- Add null/undefined checks for portfolios, accounts, and account IDs.
- Add try/catch blocks in risky operations (account processing, portfolio mapping, balance retrieval, mapper calls).
- Change top-level error handling to return an empty result instead of throwing an error.
- Implement fallback values for portfolio IDs/names, pagination, and account mappers.
- Fix EmptyResource render
=> fix: error handling and empty resource render

src/app/(routes)/accounts/page.tsx, src/app/(routes)/assets/page.tsx, src/app/(routes)/ledgers/page.tsx, src/app/(routes)/portfolios/page.tsx, src/app/(routes)/segments/page.tsx, src/app/(routes)/transactions/page.tsx, src/components/ledger-selector.tsx, src/components/pagination/index.tsx, src/hooks/use-query-params.tsx
- Added an effect to update searchValues whenever the pagination's page or limit changes
- Adjust ledger total calculation for missing items and limit overflows
=> fix: add effect to update searchValues and improve setTotal function

src/app/(routes)/ledgers/page.tsx
- Update the ledgers route by integrating a breadcrumb component
=> feat: add breadcrumb in ledgers route

src/app/(routes)/assets/assets-data-table.tsx, src/app/(routes)/segments/segments-data-table.tsx, src/app/(routes)/transactions/page.tsx, src/app/(routes)/transactions/transactions-data-table.tsx
- Remove EntityBox from the assets, segments, and transactions routes to align with the pattern used in the other routes
=> feat: remove EntityBox from assets, segments and transactions

src/lib/storage/get-storage-object.ts
=> fix: getStorageObject empty object excpetion

src/core/application/mappers/auth-mapper.ts, src/core/domain/entities/auth-entity.ts, src/core/infrastructure/midaz-plugins/auth/login/identity-auth-login-repository.ts
=> fix: update object values to snake_case from camelCase

package-lock.json, src/components/sheet/use-create-update-sheet.tsx, src/core/infrastructure/midaz-plugins/auth/login/identity-auth-login-repository.ts
=> Hotfix: Build issues

next.config.mjs, src/client/organizations.ts, src/components/organization-switcher/index.tsx, src/components/organization-switcher/organization-switcher-content.tsx
- setting next config to accept images from any url
- setting next config security policy to accept svg extension file
- setting image avatar from organization metadata when value is found
- 
=> fix: setting image avatar in organization switcher

next.config.mjs, src/components/user-dropdown/index.tsx
=> fix: trigger users client only if auth plugin is enabled

.releaserc.yml
=> breaking: update to release on v2 version

.github/workflows/release.yaml
=> breaking: breaking version to release v2

.github/workflows/release.yaml
=> breaking: force to update release version to v2

.github/workflows/build.yml, .github/workflows/release.yml
=> fix: config new flows of pipeline

src/app/(auth-routes)/signin/page.tsx
=> feat(auth): add method post attribute to signin form
